import type { ProfileConfig, TemplateDef } from "./types";

export const DEFAULT_CONFIG: ProfileConfig = {
  basics: {
    fullName: "Ada Lovelace",
    tagline: "Building delightful things for the web",
    location: "Earth, Solar System",
    workingOn: "ProfileForge 🛠️",
    learning: "Rust and WebAssembly",
    bio: "Full-stack developer who loves shipping polished products and contributing to open source.",
    funFact: "I once debugged a production issue from a train in the Alps 🚂",
  },
  tech: ["TypeScript", "React", "Next.js", "Node.js", "PostgreSQL", "Docker"],
  stats: {
    username: "octocat",
    theme: "radical",
    showStatsCard: true,
    showStreak: false,
    showTopLanguages: true,
    showTrophies: false,
    showActivityGraph: false,
  },
  socials: {
    github: "octocat",
    twitter: "",
    linkedin: "",
    devto: "",
    medium: "",
    youtube: "",
    discord: "",
    email: "",
    website: "",
  },
  extras: {
    showProfileViews: true,
    showSnake: false,
    showQuote: false,
    showSponsor: false,
    showBlogBadge: false,
    blogUrl: "",
  },
};

function clone(base: ProfileConfig, patch: Partial<ProfileConfig>): ProfileConfig {
  return {
    basics: { ...base.basics, ...(patch.basics ?? {}) },
    tech: patch.tech ?? base.tech,
    stats: { ...base.stats, ...(patch.stats ?? {}) },
    socials: { ...base.socials, ...(patch.socials ?? {}) },
    extras: { ...base.extras, ...(patch.extras ?? {}) },
  };
}

export const TEMPLATES: TemplateDef[] = [
  {
    id: "minimal",
    name: "Minimal",
    emoji: "🌙",
    description: "Clean intro, a few badges, one stats card. Less is more.",
    build: () =>
      clone(DEFAULT_CONFIG, {
        basics: {
          fullName: "Your Name",
          tagline: "Keep it simple, ship it fast",
          location: "",
          workingOn: "",
          learning: "",
          bio: "Software developer. I build things that live on the internet.",
          funFact: "",
        },
        tech: ["TypeScript", "React", "Node.js"],
        stats: {
          username: "octocat",
          theme: "dark",
          showStatsCard: true,
          showStreak: false,
          showTopLanguages: false,
          showTrophies: false,
          showActivityGraph: false,
        },
        socials: { ...DEFAULT_CONFIG.socials, github: "octocat", twitter: "octocat" },
        extras: {
          showProfileViews: true,
          showSnake: false,
          showQuote: false,
          showSponsor: false,
          showBlogBadge: false,
          blogUrl: "",
        },
      }),
  },
  {
    id: "fullstack",
    name: "Full-Stack Dev",
    emoji: "🧑‍💻",
    description: "End-to-end toolkit: web, APIs, databases, cloud and CI/CD.",
    build: () =>
      clone(DEFAULT_CONFIG, {
        basics: {
          fullName: "Alex Chen",
          tagline: "Full-stack developer • API whisperer • UI perfectionist",
          location: "San Francisco, CA",
          workingOn: "A SaaS platform for indie makers",
          learning: "Go and distributed systems",
          bio: "I design, build and ship complete products — from pixel-perfect frontends to resilient backends and cloud infrastructure.",
          funFact: "My commit streak survived two moving days and one wedding 💍",
        },
        tech: [
          "TypeScript", "JavaScript", "Python", "React", "Next.js", "Tailwind", "Redux",
          "Node.js", "Express", "NestJS", "GraphQL", "REST",
          "PostgreSQL", "MongoDB", "Redis", "Prisma",
          "Docker", "AWS", "GitHub Actions", "CI/CD", "Linux",
        ],
        stats: {
          username: "octocat",
          theme: "tokyonight",
          showStatsCard: true,
          showStreak: true,
          showTopLanguages: true,
          showTrophies: false,
          showActivityGraph: true,
        },
        socials: {
          ...DEFAULT_CONFIG.socials,
          github: "octocat",
          twitter: "octocat",
          linkedin: "octocat",
          devto: "octocat",
          website: "alexchen.dev",
        },
        extras: {
          showProfileViews: true,
          showSnake: true,
          showQuote: true,
          showSponsor: false,
          showBlogBadge: true,
          blogUrl: "blog.alexchen.dev",
        },
      }),
  },
  {
    id: "datascience",
    name: "Data Scientist",
    emoji: "🧪",
    description: "ML stack with notebooks, models and research vibes.",
    build: () =>
      clone(DEFAULT_CONFIG, {
        basics: {
          fullName: "Dr. Maya Patel",
          tagline: "Turning data into decisions 📈",
          location: "London, UK",
          workingOn: "LLM evaluation benchmarks",
          learning: "Causal inference",
          bio: "Data scientist specializing in NLP and recommendation systems. I love models that ship to production, not just slides.",
          funFact: "I have a GitHub repo of failed Kaggle experiments — my most starred project 😅",
        },
        tech: [
          "Python", "TensorFlow", "PyTorch", "scikit-learn",
          "Pandas", "NumPy", "OpenCV", "LangChain",
          "PostgreSQL", "SQLite",
          "Docker", "GCP",
        ],
        stats: {
          username: "octocat",
          theme: "gruvbox",
          showStatsCard: true,
          showStreak: false,
          showTopLanguages: true,
          showTrophies: true,
          showActivityGraph: false,
        },
        socials: {
          ...DEFAULT_CONFIG.socials,
          github: "octocat",
          linkedin: "octocat",
          medium: "octocat",
        },
        extras: {
          showProfileViews: true,
          showSnake: false,
          showQuote: true,
          showSponsor: false,
          showBlogBadge: false,
          blogUrl: "",
        },
      }),
  },
  {
    id: "student",
    name: "Student",
    emoji: "🎓",
    description: "Friendly learning-journey profile with streaks and trophies.",
    build: () =>
      clone(DEFAULT_CONFIG, {
        basics: {
          fullName: "Sam Rivera",
          tagline: "CS undergrad • learning in public 🚀",
          location: "Austin, TX",
          workingOn: "My first hackathon project",
          learning: "Data structures & algorithms",
          bio: "Computer science student exploring web dev, open source, and everything in between. Always up for a good hackathon!",
          funFact: "I wrote my first line of code to automate my homework planner 📚",
        },
        tech: [
          "JavaScript", "Python", "HTML5", "CSS3", "React", "Node.js", "Firebase", "SQLite",
        ],
        stats: {
          username: "octocat",
          theme: "radical",
          showStatsCard: true,
          showStreak: true,
          showTopLanguages: true,
          showTrophies: true,
          showActivityGraph: false,
        },
        socials: {
          ...DEFAULT_CONFIG.socials,
          github: "octocat",
          twitter: "octocat",
          youtube: "octocat",
        },
        extras: {
          showProfileViews: true,
          showSnake: true,
          showQuote: true,
          showSponsor: false,
          showBlogBadge: false,
          blogUrl: "",
        },
      }),
  },
  {
    id: "opensourceror",
    name: "Open Sourceror",
    emoji: "🧙",
    description: "Community-first profile: sponsor button, snake, the works.",
    build: () =>
      clone(DEFAULT_CONFIG, {
        basics: {
          fullName: "Robin Nakamura",
          tagline: "Maintainer • Contributor • Community builder",
          location: "Remote 🌍",
          workingOn: "Maintaining 3 OSS libraries",
          learning: "The art of saying 'PRs welcome'",
          bio: "Open source maintainer and contributor. I write docs nobody reads and tests everybody thanks me for. 💚",
          funFact: "I've contributed to repos I can't pronounce 🔤",
        },
        tech: [
          "Rust", "Go", "TypeScript", "Python",
          "React", "Svelte", "Vue",
          "Node.js", "FastAPI",
          "PostgreSQL", "Redis",
          "Docker", "Kubernetes", "Linux", "GitHub Actions",
        ],
        stats: {
          username: "octocat",
          theme: "dracula",
          showStatsCard: true,
          showStreak: true,
          showTopLanguages: true,
          showTrophies: true,
          showActivityGraph: true,
        },
        socials: {
          ...DEFAULT_CONFIG.socials,
          github: "octocat",
          twitter: "octocat",
          linkedin: "octocat",
          devto: "octocat",
          discord: "octocat",
          email: "hi@example.dev",
        },
        extras: {
          showProfileViews: true,
          showSnake: true,
          showQuote: true,
          showSponsor: true,
          showBlogBadge: true,
          blogUrl: "robin.dev/blog",
        },
      }),
  },
];
